name: New .NET Desktop
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest # For a list of available runner types, refer to
    env:
      Solution_Name: JDCLoginUI.sln # Replace with your solution name, i.e. MyWpfApp.sln.
      DOTNET_CLI_TELEMETRY_OPTOUT: 1 # TODO for what?
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Demo to test Github actions
      - name: TBR(to be removed)
        run: Echo "Hello world!!!!"

      # Install the .NET Core workload
      - name: Install .NET5.0 (version 5.0.x)
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      # BUILD ALL in the solution
      - name: Execute unit tests
        run: dotnet build
